version: "3"
services:
  registry:
    restart: always
    image: registry
    container_name: registry
    ports:
      - 5000:5000
    volumes:
      - $HOME/registry:/var/lib/registry
    user: root
